### PR TITLE
fix some complie bug with ps-lite in windows

### PR DESCRIPTION
**Pull request by yajiedesign**

### CODE REVIEW

**Comment by mli** [comment]
is it necessary to change *.pb.h? or is the windows version different to the linux version?

**Comment by yajiedesign** [comment]
@mli 
1. in cmake *.pb.h is in other path,and it is automatic generation.
2.if use fixed *.pb.h,when protobuf version not equal will compile error.

**Comment by mli** [comment]
i put the .pb.h there because `install protobuf` and compile other files using these pb.h may be in parallel for mxnet. but if it's a not problem for cmake, namely we always first install protobuf, then build ps-lite, next build mxnet, then we don't need to have these pb.hs

**Comment by yajiedesign** [comment]
@mli ok .i am Resume *.pb.h file,

**Comment by mli** [comment]
thanks, i'll figure out how to better deal with the *.pb.h files later

**Pull request merged**
